### ISSUE TITLE
Lets get rid of all the PHP and rewrite the entire thing in node.js

### ISSUE THREAD

**Issue by champfish** [pluma-lms/pluma-lms#39]

**Comment by jeffw16** [comment]
Enough with the jokes

**Comment by jeffw16** [comment]
Node.js is the archenemy of our design principles:
https://github.com/pluma-lms/pluma-lms#design-principles

**Comment by champfish** [comment]
But Node.js allows constant server client interaction. Which is needed for the type of thing Pluma is (new assignments student-student interaction etc). And our Iframewithchangingsource thing is ugly and hacky,

**Comment by champfish** [comment]
Apache2 takes longer to set up and is less cross platform (doesn't work on windows). Most of our code is HTML/JS anyways.

**Comment by jeffw16** [comment]
When you have earned your own money, you will then know how much money it costs to run a simple Node.js instance. And I'm only talking about ONE instance here.

How are we supposed to develop Node.js without a VPS with at least 1GB of RAM?

Apache has nothing to do with this. PHP is the language we're talking about here, and it certainly runs on IIS, Apache, Nginx, lighttpd, and whatever else. It is the most accessible web-based programming language and I am adamant on keeping Pluma accessible to all.

I know you want to use Node.js because WordPress.com (not WordPress itself) changed to a Node.js platform, but core WordPress is still PHP and that is why 25% of the web is powered by WordPress.

With that, I'm closing this issue until you drop at least $1,000 into this project.

**Comment by champfish** [comment]
I have my own server (8 GB Ram) that we could use. Performance isn't an issue anyhow. We would have max 2 users at any time.

**Comment by jeffw16** [comment]
I am talking about an actual server that is hosted on enterprise-quality racks, something that Digital Ocean, Amazon AWS, Heroku, OpenStack, etc. offers.

**Comment by jeffw16** [comment]
Network performance is very important and I'm sure your home server isn't on a network with enterprise-level SLAs. If we are testing from a remote location (100% of the time for me) and I cannot guarantee uptime, progress is stalled. If your machine happens to be down that day, no more progress.

**Comment by champfish** [comment]
Barring power failures, my server does not go down. I would guess network performance would be better being closer to us (LA/McKinney)

**Comment by jeffw16** [comment]
You can reopen this issue when Google hosts their servers in Larry Page's house and claims "it never goes down, barring power failures."

Seriously, you need to have backup power supplies, enterprise SLAs, reliable gigabit networks, and then we can talk. Your logic here doesn't make any sense. Just because your server is closer to where we do testing doesn't mean it is _reliable_. That is what matters.

**Comment by jeffw16** [comment]
Fixed with fork of Pluma into two codebases:
- PHP
- Node.js
